services:
  - type: web
    name: pizza-delivery-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.ethereal.email
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        value: noreply@pizzadelivery.com
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: STOCK_ALERT_THRESHOLD
        value: 20
